# Description: UdaPeople frontend stack.
# Parameters:
#   ID:
#     Description: Unique identifier.
#     Type: String
# Resources:
#   WebsiteBucket:
#     Type: AWS::S3::Bucket
#     Properties:
#       BucketName: !Sub "udapeople-${ID}"
#       AccessControl: PublicRead
#       WebsiteConfiguration:
#         IndexDocument: index.html
#         ErrorDocument: 404.html
  
#   WebsiteBucketPolicy:
#     Type: AWS::S3::BucketPolicy
#     Properties:
#       Bucket: !Ref 'WebsiteBucket'
#       PolicyDocument:
#         Statement:
#         - Sid: PublicReadForGetBucketObjects
#           Effect: Allow
#           Principal: '*'
#           Action: s3:GetObject
#           Resource: !Join ['', ['arn:aws:s3:::', !Ref 'WebsiteBucket', /*]]

# Outputs:
#   WebsiteURL:
#     Value: !GetAtt WebsiteBucket.WebsiteURL
#     Description: URL for website hosted on S3

Description: >
  Cloudfront distribution for UdaPeople.
Parameters:
  WorkflowID:
    Description: Unique identifier.
    Type: String


Resources:
  
  CloudFrontOriginAccessIdentity:
    Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: Origin Access Identity for Serverless Static Website

  WebpageCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Origins:
          - DomainName: !Sub "udapeople-${WorkflowID}.s3.amazonaws.com"
            Id: webpage
            S3OriginConfig:
              OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CloudFrontOriginAccessIdentity}"
        Enabled: True
        DefaultRootObject: index.html
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: False
          TargetOriginId: webpage
          ViewerProtocolPolicy: allow-all

Outputs:
  WorkflowID:
    Value: !Sub ${WorkflowID}
    Description: URL for website hosted on S3
    Export:
      Name: WorkflowID